version: '3.8'

services:
  db:
    image: postgres:16
    container_name: taskmanager_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: TaskManagerDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./taskmanagerapp
      dockerfile: Dockerfile
    container_name: taskmanager_backend
    ports:
      - "7152:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=TaskManagerDb;Username=admin;Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./taskmanager-ui
      dockerfile: Dockerfile
    container_name: taskmanager_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data: